# SPDX-License-Identifier: 0BSD
# Author: Makkhawan Sardlah

name: "CI"

on:
  push: 
    paths:
      - src/**
      - pyproject.toml
      - .github/workflows/**

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'
          cache: 'pip'
      - name: build
        run: pip install -e . --break-system-packages