# SPDX-License-Identifier: 0BSD
# Author: Makkhawan Sardlah

name: "BUILD"

on:
  workflow_dispatch:
  push: 
    paths:
      - src/**
      - pyproject.toml
      - .github/workflows/**

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - name: build
        run: |
            pip install . --break-system-packages
            python3 -m build
      - name: Upload Package
        uses: actions/upload-artifact@v6
        with:
          name: python-package
          path: dist/*.whl