# SPDX-License-Identifier: 0BSD
# Author: Makkhawan Sardlah

name: "CI"

on:
  push: 
    paths:
      - src/**
      - pyproject.toml
      - .github/workflows/**

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'
          cache: 'pip'
      - uses: actions/checkout@v4
      - name: build
        run: pip install -e . --break-system-packages